In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/course_lead_scoring_2026.csv')

In [3]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [4]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [5]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [6]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [7]:
numerical = list(df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index)
numerical

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score',
 'converted']

In [8]:
df[categorical] = df[categorical].fillna('NA')

In [9]:
df[numerical] = df[numerical].fillna(0.0)

In [10]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Q1

In [11]:
df.industry.value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

In [12]:
# technology

### Q2

In [13]:
df[numerical].corr()

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
annual_income,1.000000,0.161300,0.122842,0.229496,0.189652
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204,0.395038
interaction_count,0.122842,0.721609,1.000000,0.915746,0.448624
lead_score,0.229496,0.757204,0.915746,1.000000,0.483246
converted,0.189652,0.395038,0.448624,0.483246,1.000000

In [14]:
df[numerical].corr().stack().sort_values(ascending=False).reset_index()

                     level_0                   level_1         0
0              annual_income             annual_income  1.000000
1   number_of_courses_viewed  number_of_courses_viewed  1.000000
2                  converted                 converted  1.000000
3                 lead_score                lead_score  1.000000
4          interaction_count         interaction_count  1.000000
5          interaction_count                lead_score  0.915746
6                 lead_score         interaction_count  0.915746
7                 lead_score  number_of_courses_viewed  0.757204
8   number_of_courses_viewed                lead_score  0.757204
9          interaction_count  number_of_courses_viewed  0.721609
10  number_of_courses_viewed         interaction_count  0.721609
11                 converted                lead_score  0.483246
12                lead_score                 converted  0.483246
13         interaction_count                 converted  0.448624
14                 converted         interaction_count  0.448624
15                 converted  number_of_courses_viewed  0.395038
16  number_of_courses_viewed                 converted  0.395038
17             annual_income                lead_score  0.229496
18                lead_score             annual_income  0.229496
19                 converted             annual_income  0.189652
20             annual_income                 converted  0.189652
21             annual_income  number_of_courses_viewed  0.161300
22  number_of_courses_viewed             annual_income  0.161300
23             annual_income         interaction_count  0.122842
24         interaction_count             annual_income  0.122842

In [15]:
# interaction_count AND lead_score

### Q3

In [16]:
len(df)

5000

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [19]:
len(df_train), len(df_val), len(df_test)

(3000, 1000, 1000)

In [20]:
df_train = df_train.reset_index(drop=True)

In [21]:
df_val = df_val.reset_index(drop=True)

In [22]:
df_test = df_test.reset_index(drop=True)

In [23]:
y_train = df_train.converted
y_val = df_val.converted
y_test = df_test.converted

In [24]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

In [25]:
from sklearn.metrics import mutual_info_score

def mutual_info_churn_score(series):
    return mutual_info_score(series, y_train)

In [26]:
mi = df_train[categorical].apply(mutual_info_churn_score)

In [27]:
mi = mi.sort_values(ascending=False).round(2)
mi

lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64

In [28]:
# lead_source

### Q4

In [29]:
dicts = df[numerical + categorical].to_dict(orient='records')

In [31]:
numerical.remove('converted')

In [32]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[numerical + categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [33]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [34]:
val_dict = df_val[numerical + categorical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [35]:
y_pred = model.predict_proba(X_val)[:, 1]

In [36]:
converted_decision = (y_pred >= 0.5)

In [38]:
(y_val == converted_decision).mean()

np.float64(0.645)

In [39]:
(y_val == converted_decision).mean().round(2)

np.float64(0.64)

In [40]:
# 0.65

### Q5

In [41]:
original_accuracy = (y_val == converted_decision).mean()
original_accuracy

np.float64(0.645)

In [42]:
features = numerical + categorical
features

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score',
 'lead_source',
 'industry',
 'employment_status',
 'location']

In [43]:
results = {}

for excluded in features:
    selected = [f for f in features if f != excluded]

    dv = DictVectorizer(sparse=False)

    train_dict = df_train[selected].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)

    val_dict = df_val[selected].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    model = LogisticRegression(
        solver='liblinear',
        C=1.0,
        max_iter=1000,
        random_state=42
    )
    
    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5)

    accuracy = (y_val == converted_decision).mean()

    results[excluded] = original_accuracy - accuracy

In [44]:
results

{'annual_income': np.float64(-0.07899999999999996),
 'number_of_courses_viewed': np.float64(0.0020000000000000018),
 'interaction_count': np.float64(0.04400000000000004),
 'lead_score': np.float64(0.0010000000000000009),
 'lead_source': np.float64(0.0030000000000000027),
 'industry': np.float64(0.0),
 'employment_status': np.float64(0.0),
 'location': np.float64(0.0)}

In [45]:
pd.Series(results).sort_values(ascending=False)

interaction_count           0.044
lead_source                 0.003
number_of_courses_viewed    0.002
lead_score                  0.001
employment_status           0.000
industry                    0.000
location                    0.000
annual_income              -0.079
dtype: float64

In [46]:
# lead_source                  0.003
# number_of_courses_viewed     0.002
# interaction_count            0.044

In [47]:
# number_of_courses_viewed

### Q6

In [48]:
numerical

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [49]:
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [50]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[numerical + categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[numerical + categorical].to_dict(orient='records')
X_val = dv.transform(val_dict)

scores = {}

for c in [0.000001, 0.00001, 0.0001, 0.001]:
    model = LogisticRegression(
        solver='liblinear',
        C=c,
        max_iter=1000,
        random_state=42
    )
    
    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5)

    accuracy = (y_val == converted_decision).mean()

    scores[c] = round(accuracy, 3)

pd.Series(scores).sort_values(ascending=False)

0.001000    0.645
0.000100    0.613
0.000010    0.598
0.000001    0.598
dtype: float64

In [51]:
# 0.001